docs: fixing broken links in the documentation
intel/ecfw-zephyr pull request #23
Opened 2023-01-12 22:51 UTC by yerabolu

Fixing broken links in the documentation

Signed-off-by: Spoorthy Priya Yerabolu <spoorthy.priya.yerabolu@intel.com>

2023-01-13 06:36 UTC, rgundi reviewed
I see you have fixed the broken links in 2 places. The rest are all whitespace removals, right?

2023-01-13 06:36 UTC, rgundi commented on docs/reference/getting_started.html
> +<div class="highlight-bash notranslate"><div class="highlight"><pre><span></span><span class="nb">cd</span> ../ecfwwork/ecfwwork/zephyr_fork
The old link is correct. There is no need for additional "ecfwwork" folder

2023-01-18 01:59 UTC, albertofloyd requested changes
Need to update .rst files instead

2023-01-18 22:34 UTC, yerabolu commented
Closing this PR as the changes need to be done on the .RST files.

2023-01-18 22:34 UTC, closed without merging